name: IchiplforNeko
version: @version@
main: com.jp.ichi.pl.ichipl.ichiplforneko.IchiplforNeko
api-version: 1.13

commands:
  combination:
    description: combination
    aliases: [com]
    permission: op
  beam:
    description: beam
    aliases: []
    permission: op
  flykickcancel:
    description: flykickcancel
    aliases: [fkc]
    permission: ichipl.fkc
  changecolor:
    description: changecolor
    aliases: [cc]
    permission: op
  cristalrotation:
    description: cristalrotation
    aliases: [cr]
    permission: op
  movesound:
    description: movesound
    aliases: []
    permission: op
